---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
spec:
  releaseName: redis
  chart:
    spec:
      chart: ./deploy/helm/redis
      version: '0.1.*'
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 1m
  timeout: 5m
