apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metrics-server
spec:
  interval: 1m0s
  ref:
    branch: master
  timeout: 60s
  url: https://github.com/kubernetes-sigs/metrics-server
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: metrics-server
  path: ./manifests/base
  prune: true
  wait: true
  timeout: 5m0s
  patches:
    - patch: |-
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --kubelet-insecure-tls
      target:
        kind: Deployment
        name: metrics-server
        namespace: kube-system