apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ingress-nginx
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/kubernetes/ingress-nginx
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: ingress-nginx
  path: ./deploy/static/provider/kind
  prune: true
  wait: true
  timeout: 5m0s