apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ingress-nginx
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/kubernetes-sigs/kind
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: ingress-nginx
  path: ./site/static/examples/ingress/deploy-ingress-nginx.yaml
  prune: true
  wait: true
  timeout: 5m0s