controllers:
  app:
    enabled: true
    type: deployment
    serviceAccount:
        name: app
    containers:
      app:
        image:
          repository: my-registry:5001/app
          tag: latest
          pullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
            protocol: TCP
        envFrom:
          - configMapRef:
              name: "{{ .Release.Name }}-config"
          - secret: credentials
        resources:
          requests:
            cpu: "250m"
            memory: "100Mi"
          limits:
            cpu: "750m"
            memory: "2000Mi"
service:
  app:
    enabled: true
    controller: app
    type: ClusterIP
    ports:
      app:
        enabled: true
        port: 8000
        protocol: TCP
secrets:
  credentials:
    enabled: true
    stringData:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
configMaps:
  config:
    enabled: true
    data:
      ROOT_PATH: /app
      POSTGRES_DB: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_TTL: "1800"
ingress:
  app:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/x-forwarded-prefix: /app
    hosts:
      - host: localhost
        paths:
          - path: /app(/|$)(.*)
            pathType: ImplementationSpecific
            service:
              name: app
              identifier: app
              port: 8000

serviceAccount:
  extraServiceAccounts:
    app:
      name: app
      create: true

rbac:
  roles:
    app:
      forceRename: app
      enabled: true
      type: Role
      rules:
        - apiGroups: ["*"]
          resources: ["*"]
          verbs: ["get", "list", "watch"]
  bindings:
    app:
      forceRename: app
      enabled: true
      type: RoleBinding
      roleRef:
        name: app
        kind: Role
        identifier: app
      subjects:
        - kind: ServiceAccount
          name: app
          namespace: "{{ .Release.Namespace }}"

rawResources:
  hpa:
    enabled: true
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    nameOverride: "app"
    spec:
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: app
        minReplicas: 1
        maxReplicas: 10
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 70
          - type: Resource
            resource:
              name: memory
              target:
                type: Utilization
                averageUtilization: 80