name: e2e

on:
  workflow_dispatch:
  # push:
  #   branches: [ '*' ]
  #   tags-ignore: [ '*' ]

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t app:test .
      - name: Setup Flux
        uses: fluxcd/flux2/action@main
      - name: Setup Kubernetes
        id: kind
        uses: helm/kind-action@v1
        with:
          cluster_name: flux
          registry: true
          registry_name: my-registry
          registry_port: 5001
      - name: Push docker image
        env:
          LOCAL_REGISTRY: ${{ steps.kind.outputs.LOCAL_REGISTRY }}
        run: |
          docker tag app:test $LOCAL_REGISTRY/app:latest
          docker push $LOCAL_REGISTRY/app:latest
      - name: Install Flux in Kubernetes Kind
        run: flux install
      - name: Setup cluster reconciliation
        run: |
          flux create source git flux-system \
          --url=${{ github.event.repository.html_url }} \
          --branch=${GITHUB_REF#refs/heads/} \
          --username=${GITHUB_ACTOR} \
          --password=${{ secrets.GITHUB_TOKEN }}
          flux create kustomization flux-system \
          --source=flux-system \
          --path=./clusters/staging
      - name: Verify cluster reconciliation
        run: |
          kubectl -n ingress-nginx wait kustomization/ingress-nginx --for=condition=ready --timeout=5m
          kubectl -n kube-system wait kustomization/metrics-server --for=condition=ready --timeout=5m
          kubectl -n flux-system wait kustomization/apps-prerequisites --for=condition=ready --timeout=5m
          kubectl -n flux-system wait kustomization/apps --for=condition=ready --timeout=5m
      - name: Verify helm reconciliation
        run: |
          kubectl -n demo wait helmrelease/postgres --for=condition=ready --timeout=5m
          kubectl -n demo wait helmrelease/redis --for=condition=ready --timeout=5m
          kubectl -n demo wait helmrelease/app --for=condition=ready --timeout=5m
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
          flux get all --all-namespaces
