---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app
spec:
  releaseName: app
  dependsOn:
    - name: postgres
    - name: redis
    - name: ingress-nginx
      namespace: ingress-nginx
  chart:
    spec:
      chart: ./deploy/helm/app
      version: '0.1.*'
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 1m
  timeout: 5m
